version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: limone-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: limone
    volumes:
      - limone_data:/var/lib/postgresql/data

volumes:
  limone_data:
